### ISSUE TITLE
only pitch wheel messagess

### ISSUE THREAD

**Issue by SergiofBeltran** [electricityforprogress/MIDIsprout#1]
i think my device only sends pitch wheel messages, i don't know if its a problem on the code or circuit

**Comment by electricityforprogress** [comment]
Sorry this is not enough information to understand what your issue is.  What did you build, where did you get the board, what parts did you use, how did you upload the code, do you have any experience in electronics, do you have any friends or a maker-arts space who can help, what midi sound device are you using, what cables are you using? 

The device does not send pitch wheel messages at all.

The circuit works as designed and the code functions for thousands of users ... so the issue is likely in your MIDI setup or your build.

Okay, sorry now that i've been cranky about limited information in your question ... it sounds like you are using a 'bare' 328p chip which has the incorrect bootloader.  Garbled MIDI can occur if the 328p is set to 8mhz rather than 16mhz.  I will not detail the process for burning the bootloader on this old project but there are many ways to do it https://learn.adafruit.com/bootloader-basics/byob
